//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesWebApplication.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int RecipeID { get; set; }
        public int IngredientID { get; set; }
        public decimal Amount { get; set; }
        public int MeasureTypeID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual MeasureType MeasureType { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
